### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AliBawazeEer** [jbarone/xxelab#3]
Hi jbarone , 

i had to do quick practice in the lab and its working good .
i want to add more if you can go ahead and add upload functionality supports Docx and pdf file to be vulnerable to xxe which parse the document to xml like career page .

drop your mail i will try to work on it with you 

Thank you

**Comment by jbarone** [comment]
@AliBawazeEer, I'm glad to hear that you have it working. I don't really have time to modify it at the moment. But, feel free to fork the project and add the features. I'll even be happy to accept a pull request if you get them working.

Like I said before, this lab was really created as demonstration for a talk I gave on XXE. I'm glad you are finding it useful though.
